### ISSUE TITLE
Add UX to handle type.

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-seo#16]
Currently the Module assumes any content file of type "news" or "blog" should use the type "article".

The current code we have does not align with our own prefered type keyword for "news/blog" etc.. As anything of type "article" will be set as an event.

```
{{  if in (slice "blog" "news" ) .Type  }}
	{{  $s.SetInMap "seo" "type" "article"  }}
{{ else if in (slice "article") .Type }}
	{{  $s.SetInMap "seo" "type" "event"  }}
{{  end  }}
```

We should probably have a way to let the user pick their own type for any given piece of content by either:

### Creating a new parameter
```yaml
tnd_seo:
  type_mapping:
    event: event
    article: article
    video-education: video
```

### Introducing a new `seo` key "type".

This would make it easy through cascade to set an seo type to every pages of a section
```yaml
# /content/video-education/_index.md
---
title: Lesson Plans
cascade:
  seo:
    type: video
---
```
   
We should conform map performs a deep merge.
